version: "3.8"
services:
  vm:
    build: .
    privileged: true                      # required for /dev/kvm access
    devices:
      - "/dev/kvm:/dev/kvm"
    volumes:
      - ./isos:/isos                      # place ISOs here
      - ./images:/images                  # persistent qcow2 images
    ports:
      - "6080:6080"                       # noVNC web UI
      - "2222:2222"                       # optional SSH to guest (port forwarded)
      - "8000:8000"                       # VM control API
    shm_size: "1g"
    restart: unless-stopped